"""These scripts against the same vectors the client is held to.

`place.py` is a third implementation of one grammar — the client has it in TypeScript
(`src/crypto/`), the archiver in Python (`server/canvas/verifier.py`), and this is the one
handed to strangers. Three implementations that were each "checked by hand" are three chances
to be subtly wrong in different places, and the failure mode is silent: a signature that
verifies locally and is refused by the service, or worse, a sweep that differs only for text
nobody in this project happens to type.

So all three are held to the same fixture, `test/vectors/technocore-318.json`. Its provenance
is not perfect and `test/conformance.test.ts` says so at length: it comes from an open pull
request against the service, generated by its author. It is the best written-down statement of
the signed lane that exists, not an authority.

    python -m pytest test_conformance.py        (or: python test_conformance.py)
"""

from __future__ import annotations

import base64
import json
import unittest
from pathlib import Path

from place import (
    COLS,
    ROWS,
    _sign,
    _public,
    _verify,
    canonical,
    did_of,
    placement_text,
    public_key_of,
    swept,
)

VECTORS = json.loads(
    (
        Path(__file__).resolve().parents[1] / "test/vectors/technocore-318.json"
    ).read_text(encoding="utf-8")
)


def _text(code_points: list[int]) -> str:
    """Vector text is carried as code points: some swept characters have no UTF-8 encoding."""
    return "".join(chr(c) for c in code_points)


class Sweep(unittest.TestCase):
    def test_every_published_sweep_case(self) -> None:
        for case in VECTORS["sweep_cases"]:
            with self.subTest(case["name"]):
                source = _text(case["in_cp"])
                if case["raises_empty"]:
                    # The service refuses a text that sweeps to nothing. `swept` here returns
                    # the empty string and `placement_text` is what refuses, one layer up —
                    # a placement can never be empty, so the distinction costs nothing.
                    self.assertEqual(swept(source), "")
                    continue
                self.assertEqual(swept(source), _text(case["out_cp"]))

    def test_whitespace_runs_survive(self) -> None:
        # The one rule that is easy to get wrong by being helpful: a newline becomes a space,
        # and two control characters become two spaces, not one.
        self.assertEqual(swept("a\r\nc"), "a  c")


class Identities(unittest.TestCase):
    def test_did_derived_from_each_seed(self) -> None:
        for identity in VECTORS["identities"]:
            with self.subTest(identity["did"][:24]):
                seed = bytes.fromhex(identity["seed_hex"])
                self.assertEqual(did_of(_public(seed)), identity["did"])

    def test_public_key_round_trips_out_of_the_did(self) -> None:
        for identity in VECTORS["identities"]:
            with self.subTest(identity["did"][:24]):
                seed = bytes.fromhex(identity["seed_hex"])
                self.assertEqual(public_key_of(identity["did"]), _public(seed))

    def test_malformed_dids_are_refused(self) -> None:
        for case in VECTORS["did_invalid"]:
            with self.subTest(case["why"]):
                with self.assertRaises(ValueError):
                    public_key_of(case["did"])


class Signatures(unittest.TestCase):
    def test_canonical_string_matches_the_published_bytes(self) -> None:
        for case in VECTORS["signature_cases"]:
            with self.subTest(case["name"]):
                payload = canonical(
                    case["room"], int(case["nonce"]), _text(case["text_raw_cp"])
                )
                self.assertEqual(
                    payload.encode("utf-8").hex(), case["payload_utf8_hex"]
                )

    def test_signature_produced_here_matches_the_published_one(self) -> None:
        for case in VECTORS["signature_cases"]:
            with self.subTest(case["name"]):
                seed = bytes.fromhex(case["seed_hex"])
                payload = canonical(
                    case["room"], int(case["nonce"]), _text(case["text_raw_cp"])
                )
                signature = (
                    base64.urlsafe_b64encode(_sign(seed, payload.encode()))
                    .decode()
                    .rstrip("=")
                )
                self.assertEqual(signature, case["sig_canonical"])
                self.assertIn(
                    signature[-1], VECTORS["provenance"]["canonical_sig_last_chars"]
                )

    def test_every_accepted_spelling_verifies(self) -> None:
        # 86 base64url characters hold 516 bits for a 512-bit signature, so sixteen spellings
        # decode to the same bytes and the service accepts all of them. A verifier that only
        # accepts the canonical spelling rejects signatures the service considered valid.
        for case in VECTORS["signature_cases"]:
            payload = canonical(
                case["room"], int(case["nonce"]), _text(case["text_raw_cp"])
            )
            public = public_key_of(case["did"])
            for spelling in case["sig_accepted_spellings"]:
                with self.subTest(case["name"], spelling=spelling[-1]):
                    raw = base64.urlsafe_b64decode(spelling + "==")[:64]
                    self.assertTrue(_verify(public, raw, payload.encode()))

    def test_a_changed_payload_does_not_verify(self) -> None:
        case = VECTORS["signature_cases"][0]
        payload = canonical(
            case["room"], int(case["nonce"]), _text(case["text_raw_cp"])
        )
        public = public_key_of(case["did"])
        raw = base64.urlsafe_b64decode(case["sig_canonical"] + "==")[:64]
        self.assertFalse(_verify(public, raw, (payload + " ").encode()))


class PlacementGrammar(unittest.TestCase):
    """The canvas's own format, which the vectors say nothing about — it is ours."""

    def test_accepts_the_documented_shape(self) -> None:
        self.assertEqual(placement_text(12, 47, 3, "k8f2a1"), "px 12,47 3 k8f2a1")
        self.assertEqual(placement_text(0, 0, 15, "abcdef"), "px 0,0 f abcdef")

    def test_step_is_one_digit_not_decimal(self) -> None:
        # The mistake that cost 85 permanently-refused lines in the room.
        self.assertEqual(placement_text(1, 1, 12, "aaaaaa"), "px 1,1 c aaaaaa")

    def test_the_palette_past_fifteen_uses_base36(self) -> None:
        # Hex is what four bits could hold and the palette outgrew it. 1-f keep their exact
        # meaning — every pixel ever placed still means what it meant — and g-z carry the rest.
        self.assertEqual(placement_text(1, 1, 15, "aaaaaa"), "px 1,1 f aaaaaa")
        self.assertEqual(placement_text(1, 1, 16, "aaaaaa"), "px 1,1 g aaaaaa")
        self.assertEqual(placement_text(1, 1, 35, "aaaaaa"), "px 1,1 z aaaaaa")

    def test_refuses_before_signing_rather_than_after(self) -> None:
        for x, y, step, token in [
            # Two different bounds, so two cases — and read from the module rather than
            # written here, because the width has moved twice and a literal stops testing it.
            (COLS, 0, 1, "abcdef"),
            (0, ROWS, 1, "abcdef"),
            (-1, 0, 1, "abcdef"),
            (0, -1, 1, "abcdef"),
            (0, 0, 0, "abcdef"),
            (0, 0, 36, "abcdef"),
            (0, 0, 1, "abcde"),
            (0, 0, 1, "ABCDEF"),
            (0, 0, 1, "abcde!"),
        ]:
            with self.subTest(x=x, y=y, step=step, token=token):
                with self.assertRaises(ValueError):
                    placement_text(x, y, step, token)

    def test_the_far_corner_is_inside(self) -> None:
        self.assertEqual(
            placement_text(COLS - 1, ROWS - 1, 1, "abcdef"),
            f"px {COLS - 1},{ROWS - 1} 1 abcdef",
        )

    def test_a_placement_survives_the_sweep_unchanged(self) -> None:
        text = placement_text(12, 47, 3, "k8f2a1")
        self.assertEqual(swept(text), text)


if __name__ == "__main__":
    unittest.main(verbosity=2)
